version: '3'

services:

  wp:
    image: wordpress:latest
    container_name: wpapp
    ports:
      - "${WP_PORT}:80"
    volumes:
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_HOST: "${WP_DB_HOST}"
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: wpdb
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wpphpmyadmin
    ports:
      - "${PMA_PORT}:80"
    env_file:
      - ./.env
    environment:
      PMA_HOST: "${WP_DB_HOST}"
      # PMA_HOST: db
      PMA_USER: "${MYSQL_USER}"
      PMA_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    depends_on:
      - db

volumes:
  db-data:
